language: php
php:
  - 5.6
  - 5.5
  - 5.4
before_script:
  - composer install
script: ./vendor/bin/phpunit
after_script:
  - ./vendor/bin/coveralls -vvv
notifications:
  email:
    recipients:
      - kristof@2dotstwice.be
      - hans@2dotstwice.be
      - sven.houtmeyers@cultuurnet.be
